---
- name: generate locale
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8
    - ru_RU.UTF-8

- name: setup locale configuation
  copy: src=locale dest=/etc/default/locale
  # File contents can be inlined, e.g.:
  # copy: content="LC_ALL=en_US.UTF-8\nLANG=en_US.UTF-8\n" dest=/etc/default/locale
