---
- name: install postgresql and pgbouncer
  apt: name={{ item }} state=present
  with_items:
    - pgbouncer
    - postgresql-9.5
    - postgresql-client-9.5
    - postgresql-contrib-9.5
    - libpq-dev
    - python-psycopg2
